targets:
  $default:
    builders:
      flamingo_generator|field_value_generator:
        generate_for:
          include:
            - lib/model/*.dart
            - lib/**/model/*.dart
            - lib/**/controller/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/app/model/*.dart