targets:
  $default:
    builders:
      flamingo_generator|field_value_generator:
        generate_for:
          include:
            - lib/app/data/model/**/*.dart
            - lib/app/data/model/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/app/data/model/**/*.dart
            - lib/app/data/model/*.dart