name: c_school_app
description: App provide spoken chinese training

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  sort: flutter pub run import_sorter:main -e

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_performance: ^0.5.0+1
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  #  flutter_facebook_auth: "^0.2.3"
  #  twitter_login: ^2.1.3
  google_sign_in: ^4.5.9
  sign_in_with_apple: ^2.5.4
  get: ^3.26.0
  supercharged: ^2.0.0
  logger: ^0.9.4
  uuid: 2.2.2
  enum_to_string: ^1.0.14
  permission_handler: ^5.1.0+2
  flutter_sound_lite: ^7.7.0+1
  path_provider: ^1.6.27
  json_annotation: ^3.1.1
  syncfusion_flutter_charts: ^18.4.46
  material_floating_search_bar: ^0.2.6
  sticky_grouped_list: ^1.3.0
  flamingo: ^1.15.3
  flamingo_annotation: ^0.4.0
  flutter_tts: ^2.1.0
  cached_network_image: ^2.5.0
  flutter_blurhash: ^0.5.0
  keyboard_dismisser: ^1.0.2
  catcher: ^0.4.0
  sentry_flutter: ^4.0.4
  styled_widget: ^0.2.2
  wiredash: ^0.5.0
  fuzzy: ^0.3.0
  simple_animations: ^3.0.0
  sensors: ^2.0.0
  shared_preferences: ">=0.5.10 <2.0.0"
  ### Below is dependency we might consider removing
  simple_gesture_detector: ^0.2.0 # It's been maintained and expose easy to use swipe gesture
  settings_ui: ^0.6.0
  auto_size_text: ^2.1.0 # Use SelectableAutoSizeText in ui_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.4.1
  pedantic: ^1.11.0
  build_runner: ^1.11.5
  json_serializable: ^3.5.1
  flamingo_generator: ^0.8.0
  change_app_package_name: ^0.1.2
  csv: ^4.1.0
  fluttericon: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/discover_panel/
    - assets/main_app/
    - assets/login/
    - assets/study_panel/
    - assets/review_panel/
    - assets/setting_panel/
    - assets/splash/
    - assets/upload/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family:  CSchool
      fonts:
        - asset: assets/fonts/CSchool.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
