name: c_school_app
description: App provide spoken chinese training

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  sort: flutter pub run import_sorter:main -e
  fix: dart fix --apply

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.3
  firebase_analytics: ^8.0.0
  firebase_performance: ^0.7.0
  firebase_auth: ^1.1.0
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  #  flutter_facebook_auth: "^0.2.3"
  #  twitter_login: ^2.1.3
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.0.0
  get: ^4.1.4
  supercharged: ^2.0.0
  logger: ^1.0.0
  uuid: ^3.0.4
  enum_to_string: ^2.0.1
  permission_handler: ^8.1.1
  flutter_sound_lite: ^8.1.1
  just_audio: ^0.7.4
  path_provider: ^2.0.1
  json_annotation: ^4.0.1
  syncfusion_flutter_charts: ^19.1.56
  material_floating_search_bar: ^0.3.4
  sticky_grouped_list: ^1.3.0
  flamingo: ^2.5.1
  flamingo_annotation: ^0.5.0
  flutter_tts: ^3.0.0
  cached_network_image: ^3.0.0
  flutter_blurhash: ^0.6.0
  keyboard_dismisser: ^2.0.0
  catcher: ^0.6.5
  sentry_flutter: ^5.0.0
  styled_widget: ^0.3.0
  wiredash: ^0.7.0+1
  fuzzy: ^0.4.0-nullsafety.0
  simple_animations: ^3.0.3
  sensors: ^2.0.0
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.4
  ### Below is dependency we might consider removing
  simple_gesture_detector: ^0.2.0 # It's been maintained and expose easy to use swipe gesture
  settings_ui: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0  # Use SelectableAutoSizeText in ui_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.4.3
  pedantic: ^1.11.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.0
  flamingo_generator: ^0.11.0
  change_app_package_name: ^1.0.0
  csv: ^5.0.0
  fluttericon: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/discover_panel/
    - assets/main_app/
    - assets/login/
    - assets/study_panel/
    - assets/review_panel/
    - assets/setting_panel/
    - assets/splash/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family:  CSchool
      fonts:
        - asset: assets/fonts/CSchool.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
